"""Auto-generated votes table

Revision ID: 4199fd6dcec3
Revises: e55d11f832bc
Create Date: 2023-03-04 16:37:44.906935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4199fd6dcec3'
down_revision = 'e55d11f832bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.add_column('posts', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'rating')
    op.drop_table('votes')
    # ### end Alembic commands ###
